[{
    "mode": "supply",
    "url": "#",
    "photo": "images/l1.jpg",
    "desc": "上海地区50人展厅",
    "count": "20",
    "author": "Cary",
    "school": "复旦大学",
    "datatime": "2017-12-30",
    "sum": "1000",
    "tags": "自营"
  },
  {
    "mode": "supply",
    "url": "#",
    "photo": "images/l1.jpg",
    "desc": "上海地区20人展厅",
    "count": "10",
    "author": "Shelly",
    "school": "清华大学",
    "datatime": "2017-12-30",
    "sum": "100",
    "tags": "优质"
  },
  {
    "mode": "demand",
    "url": "#",
    "photo": "images/l1.jpg",
    "desc": "上海地区100人展厅",
    "count": "20",
    "author": "Cary",
    "school": "复旦大学",
    "datatime": "2017-12-30",
    "sum": "200",
    "tags": "自营"
  },
  {
    "mode": "supply",
    "url": "#",
    "photo": "images/l1.jpg",
    "desc": "上海地区50人展厅",
    "count": "20",
    "author": "Cary",
    "school": "复旦大学",
    "datatime": "2017-12-30",
    "sum": "1000",
    "tags": "自营"
  },
  {
    "mode": "demand",
    "url": "#",
    "photo": "images/l1.jpg",
    "desc": "上海地区20人展厅",
    "count": "10",
    "author": "Shelly",
    "school": "清华大学",
    "datatime": "2017-12-30",
    "sum": "100",
    "tags": "优质"
  },
  {
    "mode": "demand",
    "url": "#",
    "photo": "images/l1.jpg",
    "desc": "上海地区100人展厅",
    "count": "20",
    "author": "Cary",
    "school": "复旦大学",
    "datatime": "2017-12-30",
    "sum": "200",
    "tags": "自营"
  }, {
    "mode": "supply",
    "url": "#",
    "photo": "images/l1.jpg",
    "desc": "上海地区50人展厅",
    "count": "20",
    "author": "Cary",
    "school": "复旦大学",
    "datatime": "2017-12-30",
    "sum": "1000",
    "tags": "自营"
  },
  {
    "mode": "demand",
    "url": "#",
    "photo": "images/l1.jpg",
    "desc": "上海地区20人展厅",
    "count": "10",
    "author": "Shelly",
    "school": "清华大学",
    "datatime": "2017-12-30",
    "sum": "100",
    "tags": "优质"
  },
  {
    "mode": "demand",
    "url": "#",
    "photo": "images/l1.jpg",
    "desc": "上海地区100人展厅",
    "count": "20",
    "author": "Cary",
    "school": "复旦大学",
    "datatime": "2017-12-30",
    "sum": "200",
    "tags": "自营"
  },
  {
    "mode": "demand",
    "url": "#",
    "photo": "images/l1.jpg",
    "desc": "上海地区20人展厅",
    "count": "10",
    "author": "Shelly",
    "school": "清华大学",
    "datatime": "2017-12-30",
    "sum": "100",
    "tags": "优质"
  }
]
